dist: bionic
language: cpp
compiler: gcc
#sudo: required

addons:
  apt:
    packages:
     - build-essential
     - default-jdk
     - libboost-dev
     - zlib1g-dbg
     - libgoogle-perftools-dev
     - systemtap-sdt-dev
     - python3
     - python3-pip

script:
 - make
 - make run_tests
 - make run_trt_tests
 - make python/pyudepot/libpyudepot.so
 - pip3 install numpy
 - make run_pyudepot_test

notifications:
  email:
    recipients:
      - nio@zurich.ibm.com
    on_success: never # default: change
    on_failure: always # default: always
