dist: bionic
language: cpp
compiler: gcc
#sudo: required

addons:
  apt:
    packages:
     - build-essential
     - default-jdk
     - libboost-dev
     - zlib1g-dbg
     - libgoogle-perftools-dev
     - systemtap-sdt-dev

script:
 - make
 - rm -f /dev/shm/udepot-test
 - LD_LIBRARY_PATH=$(JNI_DIR):$$LD_LIBRARY_PATH java -cp src/uDepot/jni/classes/:test/jni/ uDepotJNITest /dev/shm/udepot-test
# - make run_tests
# - make run_trt_tests

notifications:
  email:
    recipients:
      - nio@zurich.ibm.com
      - ddi@zurich.ibm.com
    on_success: never # default: change
    on_failure: always # default: always
